- java/hnefatafl.java
- java/sideBar.java
We initially said we wanted the turn number as well as the player's turn (black or white) in the side bar as well. However, I tired it but it is far too congested. Therefore, I think those two things should go into a new JPanel at the bottom.
> Side bar skeleton with some basic functionality

- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/Hnefatafl.java
Added highlight/unhighlight methods. Added corner/center board spot to board matrix
> Newbranch1

- src/main/java/copenhagen/BlackWhiteStart.java
- src/main/java/copenhagen/FinalMenu.java
- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/MainMenu.java
Also added pack() to JFrames before they display to help and try alleviate the
lag before the game displays
> main menu disappears after clicking option

- src/main/java/copenhagen/BottomBar.java
- src/main/java/copenhagen/Hnefatafl.java
The program now as a bottom bar that contains the current turn number and whose turn it is. The game now works for only one side can move a piece at a time now.
> Turn number and player's turn

- src/main/java/copenhagen/GameRules.java
Made it so the game rules message is displayed in a normal sized window with scroll functionality
> Fix game rules frame size issue

- src/main/java/copenhagen/BlackWhiteStart.java
- src/main/java/copenhagen/FinalMenu.java
- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/GameRules.java
- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/MainMenu.java
- src/main/java/copenhagen/MenuBar.java
- src/main/java/copenhagen/SideBar.java
I added Javadoc comments to everything. I also removed unused imports and variables and eliminated some extra whitespace.
> Javadoc comments

- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/Hnefatafl.java
Game pieces now move in only legal moves. I also managed to fix the corner and center square issues with the color being overwritten. The findShieldwall function can and probably should be refactored if someone figures out an efficient way to do so.
> Capturing pieces functionality

- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/SaveAndLoad.java
- src/test/java/copenhagen/SaveAndLoadTest.java
> refactorSandL

- src/main/java/copenhagen/SaveAndLoad.java
- src/test/java/copenhagen/SaveAndLoadTest.java
Adding tests for save and load
> Save and load tests

- src/main/java/copenhagen/GameLogic.java
Just added an empty gamelogic class for now.  haven't added any of the refactored code yet but I think this might reduce some merge conflicts if we all use the same class...
> adding gamelogic.java file

- src/main/java/copenhagen/BoardLocation.java
- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/Hnefatafl.java
Created a new class for locations on board with a row and column to make selectedLoc variable more object-orieinted
> add row/column location class

- build.gradle
- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/GameLogic.java
- src/main/java/copenhagen/Hnefatafl.java
- src/test/java/copenhagen/GameLogicTest.java
I believe the pieceLayout variable in Hnefatafl.java can eventually be completely removed.
> Refactoring some game logic

- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/GameLogic.java
- src/main/java/copenhagen/Hnefatafl.java
- src/test/java/copenhagen/ValidMovesTest.java
fixed the valid moves to so that it test the valid moves from every square with the pieces in their initial locations. I wanted to add the tests to the game logic test class but they failed while in there so I kept them as their own class. In the future they should probably be moved to be with the other game logic tests.
> fix test for valid moves

- src/main/java/copenhagen/GameLogic.java
- src/test/java/copenhagen/ValidMovesTest.java
I fixed the getValidMoves method to allow all pieces to pass over the center square but only the king to land on it. Previously, the king could pass over the center square but other pieces could not. The king is still the only piece that can land on the center square.
> Update getValidMoves to follow copenhagen rules

- src/main/java/copenhagen/FinalMenu.java
- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/GameLogic.java
- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/MainMenu.java
- src/main/java/copenhagen/SaveAndLoad.java
- src/main/java/copenhagen/SideBar.java
- src/test/java/copenhagen/GameLogicTest.java
- src/test/java/copenhagen/HnefataflTest.java
- src/test/java/copenhagen/SaveAndLoadTest.java
- src/test/java/copenhagen/ValidMovesTest.java
Did numerous things in this branch. The biggest thing was getting the load to function properly. Now save files can be loaded and the game will run.
I also did numerous small fixes in spelling or formatting as well as adding some more unit tests.
Also changed concede button to display the final menu instead of just exiting and have the save prompt only come up when necessary.
> loading game file works + small mistake fixes and adding tests

- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/SideBar.java
fixes the bug where the old game board screen would still be on the
screen after loading a new game.
> fixes old game board screen bug

- src/main/java/copenhagen/GameBoard.java
- src/main/java/copenhagen/GameLogic.java
- src/main/java/copenhagen/Hnefatafl.java
- src/test/java/copenhagen/GameLogicTest.java
Little bit of refactoring and I realized that the win scenario where the attackers surround the defenders wasn't working correctly so I took that win scenario out for now.
> Refactor Pete

- src/main/java/copenhagen/BottomBar.java
- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/SaveAndLoad.java
- src/test/java/copenhagen/HnefataflTest.java
- src/test/java/copenhagen/SaveAndLoadTest.java
Save and load now work with the game clock. It still needs some cleaning up though, which I'll do tomorrow.
> saveandload

- src/main/java/copenhagen/BottomBar.java
- src/main/java/copenhagen/GameLogic.java
- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/SideBar.java
This fixes a problem where the clocks would not be reset properly when
a game is loaded from file. It would display the correct time but that
was not the same time that was being tracked. So a player would be
declared winner in the newly loaded game when the timer from the
previous game expired. 
I also made it so the clocks stop ticking when a button in the sidebar is pressed. The clocks start back up when whatever menu was opened has been closed.
> Fix clock bugs 

- src/main/java/copenhagen/CountDownTimer.java
- src/main/java/copenhagen/FinalMenu.java
This fixed an issue that caused the clocks to not be reset after a loaded game
ends and a new game begins. Also fixed a small issue where 2 final menus would pop up if a player lost by running out of time.
> Fix timer issues

- src/main/java/copenhagen/BottomBar.java
- src/main/java/copenhagen/CountDownTimer.java
- src/main/java/copenhagen/Hnefatafl.java
- src/main/java/copenhagen/SideBar.java
This FINALLY fixes the issues with the timer when a new game is loaded in the middle of an on-going game.
> FINALLY fix timer bug

- src/main/java/copenhagen/BoardLocation.java
- src/main/java/copenhagen/BottomBar.java
- src/main/java/copenhagen/Clock.java
- src/main/java/copenhagen/FinalMenu.java
- src/main/java/copenhagen/GameLogic.java
- src/main/java/copenhagen/Hnefatafl.java
- src/test/java/copenhagen/ClockTest.java
- src/test/java/copenhagen/GameLogicTest.java
- src/test/java/copenhagen/HnefataflTest.java
- src/test/java/copenhagen/SaveAndLoadTest.java
Look at older commits in this branch to see the defect fix. Just added comments and fixed some comments so that everything was uniform. Added a couple more unit tests as well.
> unit tests, comments, and defect fix
